import type { Metadata } from "next";
import "./globals.css";
import { tournament } from "@/lib/config";
import Navbar from "@/components/Navbar";
import FooterSponsors from "@/components/FooterSponsors";
import Link from "next/link";

const siteUrl = "https://www.respawnlb.com";
const ogDescription = `${tournament.organizer} × ${tournament.partner} present a 5v5 CS2 showdown for a ${tournament.prizePool} prize pool. Lock your team's slot — registration closes ${tournament.registrationClosesDaysBefore} days before kickoff.`;

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: `${tournament.shortName} — ${tournament.prizePool} CS2 Tournament`,
  description: ogDescription,
  openGraph: {
    type: "website",
    siteName: tournament.name,
    url: siteUrl,
    title: `${tournament.shortName} — ${tournament.prizePool} CS2 Tournament`,
    description: ogDescription,
    // og image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: `${tournament.shortName} — ${tournament.prizePool} CS2 Tournament`,
    description: ogDescription,
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Tektur:wght@500;700;900&family=Chakra+Petch:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-screen flex flex-col">
        <Navbar />
        <main className="flex-1">{children}</main>
        <footer className="border-t border-edge/60 mt-20">
          <FooterSponsors />
          <div className="mx-auto max-w-6xl px-4 py-10 flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/logo.png"
                alt="Respawn Gaming Lounge"
                className="h-14 w-auto drop-shadow-[0_0_18px_rgba(168,85,247,0.45)]"
              />
              <span className="text-lg text-muted/50">×</span>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src="/lerf.webp" alt={tournament.partner} className="h-7 w-auto opacity-80" />
              <span className="ml-1 text-sm text-muted">
                © {new Date().getFullYear()} {tournament.organizer} × {tournament.partner}
              </span>
            </div>
            <nav className="flex items-center gap-6 text-sm text-muted">
              <Link href="/rules" className="hover:text-neon-cyan transition-colors">Rules</Link>
              <Link href="/teams" className="hover:text-neon-cyan transition-colors">Teams</Link>
              <Link href="/status" className="hover:text-neon-cyan transition-colors">Check Status</Link>
              <Link href="/admin" className="hover:text-neon-magenta transition-colors">Admin</Link>
            </nav>
          </div>
        </footer>
      </body>
    </html>
  );
}
