import type { Metadata } from "next";
import "./globals.css";
import { tournament } from "@/lib/config";
import Navbar from "@/components/Navbar";
import FooterSponsors from "@/components/FooterSponsors";
import Link from "next/link";
import { Analytics } from "@vercel/analytics/next";

const siteUrl = "https://www.respawnlb.com";
const defaultTitle = `${tournament.shortName} - ${tournament.prizePool} CS2 Tournament in Lebanon`;
const ogDescription =
  `${tournament.organizer}, Lebanon's esports gaming lounge, × ${tournament.partner} present a 5v5 CS2 showdown ` +
  `for a ${tournament.prizePool} prize pool - online on Faceit, with live semifinals and finals at the lounge. ` +
  `Lock your team's slot - registration closes ${tournament.registrationClosesDaysBefore} days before kickoff.`;

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: defaultTitle,
    template: `%s | ${tournament.organizer}`,
  },
  description: ogDescription,
  applicationName: tournament.name,
  keywords: [
    "gaming lounge Lebanon",
    "best gaming lounge Lebanon",
    "esports Lebanon",
    "esports tournament Lebanon",
    "CS2 tournament",
    "CS2 tournament Lebanon",
    "Counter-Strike 2 Lebanon",
    "Faceit tournament",
    "gaming tournament Lebanon",
    "LAN finals Lebanon",
    "Respawn Gaming Lounge",
    "LERF",
    "Lebanese Esports Federation",
    tournament.name,
  ],
  alternates: { canonical: "/" },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  openGraph: {
    type: "website",
    siteName: tournament.name,
    url: siteUrl,
    locale: "en_US",
    title: defaultTitle,
    description: ogDescription,
    // og image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: defaultTitle,
    description: ogDescription,
  },
};

/**
 * Structured data so search engines understand who Respawn is (Organization)
 * and can surface the tournament as an Event in results. Rendered once,
 * site-wide.
 */
const jsonLd = [
  {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": `${siteUrl}/#organization`,
    name: tournament.organizer,
    url: siteUrl,
    logo: `${siteUrl}/logo.png`,
    description:
      "Respawn Gaming Lounge is a gaming lounge and esports venue in Lebanon hosting CS2 and other competitive gaming tournaments.",
    telephone: tournament.contactPhone,
    sameAs: [tournament.discordServerUrl],
    areaServed: { "@type": "Country", name: "Lebanon" },
  },
  {
    "@context": "https://schema.org",
    "@type": "Event",
    name: tournament.name,
    description:
      `5v5 Counter-Strike 2 tournament with a ${tournament.prizePool} prize pool, organized by ${tournament.organizer} × ${tournament.partner}. ` +
      "Played online on Faceit; semifinals and finals live at Respawn Gaming Lounge, Lebanon.",
    startDate: tournament.startDate,
    eventStatus: "https://schema.org/EventScheduled",
    eventAttendanceMode: "https://schema.org/MixedEventAttendanceMode",
    image: `${siteUrl}/logo.png`,
    url: siteUrl,
    location: [
      { "@type": "VirtualLocation", url: "https://www.faceit.com" },
      {
        "@type": "Place",
        name: tournament.organizer,
        address: { "@type": "PostalAddress", addressCountry: "LB" },
      },
    ],
    organizer: { "@id": `${siteUrl}/#organization` },
    offers: {
      "@type": "Offer",
      name: "Team entry fee",
      price: "125",
      priceCurrency: "USD",
      url: `${siteUrl}/register`,
      availability: "https://schema.org/LimitedAvailability",
    },
  },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Tektur:wght@500;700;900&family=Chakra+Petch:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap"
          rel="stylesheet"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-screen flex flex-col">
        <Navbar />
        <main className="flex-1">{children}</main>
        <footer className="border-t border-edge/60 mt-20">
          <FooterSponsors />
          <div className="mx-auto max-w-6xl px-4 py-10 flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/logo.png"
                alt="Respawn Gaming Lounge"
                className="h-14 w-auto drop-shadow-[0_0_18px_rgba(168,85,247,0.45)]"
              />
              <span className="text-lg text-muted/50">×</span>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src="/lerf.webp" alt={tournament.partner} className="h-7 w-auto opacity-80" />
              <span className="ml-1 text-sm text-muted">
                © {new Date().getFullYear()} {tournament.organizer} × {tournament.partner}
              </span>
            </div>
            <nav className="flex items-center gap-6 text-sm text-muted">
              <Link href="/rules" className="hover:text-neon-cyan transition-colors">Rules</Link>
              <Link href="/teams" className="hover:text-neon-cyan transition-colors">Teams</Link>
              <Link href="/status" className="hover:text-neon-cyan transition-colors">Check Status</Link>
              <Link href="/admin" className="hover:text-neon-magenta transition-colors">Admin</Link>
            </nav>
          </div>
        </footer>
        <Analytics />
      </body>
    </html>
  );
}
