import type { Metadata } from "next";
import "./globals.css";
import { lounge, routes, tournament } from "@/lib/config";
import Navbar from "@/components/Navbar";
import FooterSponsors from "@/components/FooterSponsors";
import HideOnRoutes from "@/components/HideOnRoutes";
import SocialLinks from "@/components/SocialLinks";
import ScrollProgress from "@/components/ScrollProgress";
import Link from "next/link";
import { Analytics } from "@vercel/analytics/next";

const siteUrl = "https://www.respawnlb.com";
const defaultTitle = `${lounge.name} - Esports & Gaming Lounge in Lebanon`;
const siteDescription =
  `${lounge.name} is a gaming lounge and esports venue in Lebanon: open play on serious hardware, ` +
  `and the stage where the country's biggest Tournaments are played live in front of a crowd. ` +
  `Home of ${tournament.name}, a ${tournament.prizePool} CS2 tournament.`;

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: defaultTitle,
    template: `%s | ${lounge.name}`,
  },
  description: siteDescription,
  applicationName: lounge.name,
  keywords: [
    "gaming lounge Lebanon",
    "best gaming lounge Lebanon",
    "esports Lebanon",
    "esports venue Lebanon",
    "esports tournament Lebanon",
    "CS2 tournament",
    "CS2 tournament Lebanon",
    "Counter-Strike 2 Lebanon",
    "Faceit tournament",
    "gaming tournament Lebanon",
    "LAN finals Lebanon",
    "Respawn Gaming Lounge",
    "LERF",
    "Lebanese Esports Federation",
    tournament.name,
  ],
  alternates: { canonical: "/" },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  openGraph: {
    type: "website",
    siteName: lounge.name,
    url: siteUrl,
    locale: "en_US",
    title: defaultTitle,
    description: siteDescription,
    // og image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: defaultTitle,
    description: siteDescription,
  },
};

/**
 * Site-wide structured data describes the business. The tournament's Event
 * markup lives in the /tournaments/heatwave2026 layout, so it only appears
 * on pages that are actually about that event.
 */
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": `${siteUrl}/#organization`,
  name: lounge.name,
  url: siteUrl,
  logo: `${siteUrl}/logo.png`,
  description: lounge.blurb,
  telephone: lounge.phone,
  sameAs: [lounge.discordUrl, lounge.instagramUrl, lounge.tiktokUrl].filter(Boolean),
  areaServed: { "@type": "Country", name: "Lebanon" },
  ...(lounge.address ? { address: { "@type": "PostalAddress", streetAddress: lounge.address, addressCountry: "LB" } } : {}),
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Tektur:wght@500;700;900&family=Chakra+Petch:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap"
          rel="stylesheet"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-screen flex flex-col">
        <ScrollProgress />
        <Navbar />
        <main className="flex-1">{children}</main>
        <footer className="border-t border-edge/60 mt-20">
          {/* Sponsors are the tournament's, not the lounge's - keep the strip
              off the landing page. */}
          <HideOnRoutes routes={["/"]}>
            <FooterSponsors />
          </HideOnRoutes>
          <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 px-4 py-10 lg:flex-row">
            <div className="flex items-center gap-3">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/logo.png"
                alt={lounge.name}
                className="h-14 w-auto drop-shadow-[0_0_18px_rgba(168,85,247,0.45)]"
              />
              <span className="ml-1 text-sm text-muted">
                © {new Date().getFullYear()} {lounge.name}
              </span>
            </div>
            <SocialLinks />

            <nav className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm text-muted">
              <Link href={routes.tournament} className="hover:text-neon-cyan transition-colors">
                {tournament.shortName}
              </Link>
              <Link href={routes.prizes} className="hover:text-neon-cyan transition-colors">Prizes</Link>
              <Link href={routes.rules} className="hover:text-neon-cyan transition-colors">Rules</Link>
              <Link href={routes.review} className="hover:text-neon-cyan transition-colors">Review</Link>
              <Link href={routes.sponsors} className="hover:text-neon-cyan transition-colors">Sponsors</Link>
              <Link href="/admin" className="hover:text-neon-magenta transition-colors">Admin</Link>
            </nav>
          </div>
        </footer>
        <Analytics />
      </body>
    </html>
  );
}
